/** Jest config for Release Manager (main process lib + runInDir/project logic) */
module.exports = {
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.js'],
  roots: ['<rootDir>'],
  testPathIgnorePatterns: ['/node_modules/'],
  collectCoverageFrom: [
    'src-main/lib/composer.js',
    'src-main/lib/config.js',
    'src-main/lib/conventionalCommits.js',
    'src-main/lib/coverageParse.js',
    'src-main/lib/documentation.js',
    'src-main/lib/gitDiff.js',
    'src-main/lib/gitLog.js',
    'src-main/lib/gitPorcelain.js',
    'src-main/lib/github.js',
    'src-main/lib/githubErrors.js',
    'src-main/lib/migration.js',
    'src-main/lib/ollama.js',
    'src-main/lib/packageJson.js',
    'src-main/lib/packageManagers.js',
    'src-main/lib/projectDetection.js',
    'src-main/lib/projectTestScripts.js',
    'src-main/lib/projects.js',
    'src-main/lib/releaseStrategy.js',
    'src-main/lib/runInDir.js',
    'src-main/lib/shortcuts.js',
    'src-main/lib/theme.js',
    'src-main/lib/version.js',
    'src-main/lib/git/index.js',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  coverageThreshold: {
    global: {
      statements: 100,
      branches: 100,
      functions: 100,
      lines: 100,
    },
  },
  verbose: true,
};
