const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('releaseManager', {
  getProjects: () => ipcRenderer.invoke('rm-get-projects'),
  getAllProjectsInfo: () => ipcRenderer.invoke('rm-get-all-projects-info'),
  setProjects: (projects) => ipcRenderer.invoke('rm-set-projects', projects),
  showDirectoryDialog: () => ipcRenderer.invoke('rm-show-directory-dialog'),
  getProjectInfo: (dirPath) => ipcRenderer.invoke('rm-get-project-info', dirPath),
  versionBump: (dirPath, bump) => ipcRenderer.invoke('rm-version-bump', dirPath, bump),
  gitTagAndPush: (dirPath, tagMessage) => ipcRenderer.invoke('rm-git-tag-and-push', dirPath, tagMessage),
  release: (dirPath, bump, force, options) => ipcRenderer.invoke('rm-release', dirPath, bump, force, options),
  getCommitsSinceTag: (dirPath, sinceTag) => ipcRenderer.invoke('rm-get-commits-since-tag', dirPath, sinceTag),
  getRecentCommits: (dirPath, n) => ipcRenderer.invoke('rm-get-recent-commits', dirPath, n),
  getSuggestedBump: (commits) => ipcRenderer.invoke('rm-get-suggested-bump', commits),
  getShortcutAction: (viewMode, selectedPath, key, metaKey, ctrlKey, inInput) =>
    ipcRenderer.invoke('rm-get-shortcut-action', viewMode, selectedPath, key, metaKey, ctrlKey, inInput),
  getActionsUrl: (gitRemote) => ipcRenderer.invoke('rm-get-actions-url', gitRemote),
  getGitHubToken: () => ipcRenderer.invoke('rm-get-github-token'),
  setGitHubToken: (token) => ipcRenderer.invoke('rm-set-github-token', token),
  getOllamaSettings: () => ipcRenderer.invoke('rm-get-ollama-settings'),
  setOllamaSettings: (baseUrl, model) => ipcRenderer.invoke('rm-set-ollama-settings', baseUrl, model),
  ollamaListModels: (baseUrl) => ipcRenderer.invoke('rm-ollama-list-models', baseUrl),
  ollamaGenerateCommitMessage: (dirPath) => ipcRenderer.invoke('rm-ollama-generate-commit-message', dirPath),
  ollamaGenerateReleaseNotes: (dirPath, sinceTag) => ipcRenderer.invoke('rm-ollama-generate-release-notes', dirPath, sinceTag),
  getGitStatus: (dirPath) => ipcRenderer.invoke('rm-get-git-status', dirPath),
  commitChanges: (dirPath, message) => ipcRenderer.invoke('rm-commit-changes', dirPath, message),
  copyToClipboard: (text) => ipcRenderer.invoke('rm-copy-to-clipboard', text),
  openPathInFinder: (dirPath) => ipcRenderer.invoke('rm-open-path-in-finder', dirPath),
  openInTerminal: (dirPath) => ipcRenderer.invoke('rm-open-in-terminal', dirPath),
  openInEditor: (dirPath) => ipcRenderer.invoke('rm-open-in-editor', dirPath),
  getReleasesUrl: (gitRemote) => ipcRenderer.invoke('rm-get-releases-url', gitRemote),
  syncFromRemote: (dirPath) => ipcRenderer.invoke('rm-sync-from-remote', dirPath),
  getGitHubReleases: (gitRemote) => ipcRenderer.invoke('rm-get-github-releases', gitRemote),
  downloadLatestRelease: (gitRemote) => ipcRenderer.invoke('rm-download-latest', gitRemote),
  downloadAsset: (url, suggestedFileName) => ipcRenderer.invoke('rm-download-asset', url, suggestedFileName),
  openUrl: (url) => ipcRenderer.invoke('rm-open-url', url),
  getAppInfo: () => ipcRenderer.invoke('rm-get-app-info'),
  getChangelog: () => ipcRenderer.invoke('rm-get-changelog'),
  getTheme: () => ipcRenderer.invoke('rm-get-theme'),
  setTheme: (theme) => ipcRenderer.invoke('rm-set-theme', theme),
  onTheme: (callback) => {
    ipcRenderer.on('rm-theme', (_e, effective) => callback(effective));
  },
});
